import type { Lesson } from "@/lib/types";

/**
 * MATH Year 10, 11, 12 — completes the pathway.
 * Y10: Victorian Curriculum F–10 v2.0 Level 10.
 * Y11/Y12: builds on the existing "calculus-limits" (Y11) and
 * "probability-distributions" (Y12) lessons already in lessons.ts —
 * VCE Mathematical Methods Units 1–4 style trajectory.
 * Import and spread into LESSONS in src/content/lessons.ts.
 */
export const MATH_Y10_Y12_LESSONS: Lesson[] = [
  // ─── Year 10 ───
  {
    id: "y10-quadratics-completing-square",
    title: "Completing the Square & Quadratic Applications",
    summary: "30-min block: completing the square, turning point form, and real-world quadratic problems (projectiles, area).",
    estimatedMinutes: 30,
    year: 10,
    subject: "math",
    strand: "Algebra",
    content: [
      { type: "heading", text: "Turning point form" },
      { type: "paragraph", text: "Completing the square rewrites ax²+bx+c as a(x−h)²+k, instantly revealing the turning point (h, k)." },
      { type: "example", title: "Complete the square: x²+6x+5", body: "x²+6x+9−9+5 = (x+3)²−4. Turning point: (−3, −4)." },
      { type: "callout", tone: "tip", text: "This form is exactly how you'd model a ball's height over time, or find the dimensions that maximise a rectangular area." },
    ],
    quiz: [
      { id: "q1", prompt: "Complete the square: x²+4x+1", options: ["(x+2)²−3", "(x+2)²+3", "(x+4)²−15", "(x+2)²−1"], correctIndex: 0, explanation: "x²+4x+4−4+1=(x+2)²−3." },
      { id: "q2", prompt: "Turning point of y=(x−2)²+7:", options: ["(2,7)", "(−2,7)", "(2,−7)", "(7,2)"], correctIndex: 0, explanation: "Vertex form (x−h)²+k gives turning point (h,k)." },
      { id: "q3", prompt: "A ball's height is h=−5t²+20t. Time to reach max height (vertex t-value)?", options: ["1s", "2s", "4s", "5s"], correctIndex: 1, explanation: "t=−b/2a=−20/(2×−5)=2." },
      { id: "q4", prompt: "Complete the square: x²−8x", options: ["(x−4)²−16", "(x−8)²−64", "(x−4)²+16", "(x−4)²"], correctIndex: 0, explanation: "x²−8x+16−16=(x−4)²−16." },
      { id: "q5", prompt: "y=(x+3)²−4 has turning point:", options: ["(3,−4)", "(−3,−4)", "(−3,4)", "(4,3)"], correctIndex: 1, explanation: "h=−3, k=−4." },
      { id: "q6", prompt: "The turning point of a parabola is also called the:", options: ["Root", "Vertex", "Axis", "Intercept"], correctIndex: 1, explanation: "Vertex is the standard term." },
    ],
  },
  {
    id: "y10-trig-sine-cosine-rules",
    title: "Trigonometry: Sine & Cosine Rules",
    summary: "30-min block: solving non-right-angled triangles using the sine and cosine rules.",
    estimatedMinutes: 30,
    year: 10,
    subject: "math",
    strand: "Measurement · Trigonometry",
    content: [
      { type: "formula", latex: "\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}", note: "Sine rule — use when you have an angle-side opposite pair" },
      { type: "formula", latex: "c^2=a^2+b^2-2ab\\cos C", note: "Cosine rule — use for SAS or SSS" },
      { type: "example", title: "Sine rule example", body: "a=10, A=40°, B=60°. b/sin60° = 10/sin40° → b ≈ 13.5." },
      { type: "callout", tone: "tip", text: "Sine rule: angle-side pairs. Cosine rule: two sides + included angle, or all three sides." },
    ],
    quiz: [
      { id: "q1", prompt: "The sine rule is used when you know:", options: ["Three sides only", "An angle and its opposite side, plus one more piece", "Only right angles", "Nothing"], correctIndex: 1, explanation: "Sine rule needs an angle-side opposite pair." },
      { id: "q2", prompt: "Cosine rule is best for:", options: ["Two angles only", "Two sides + included angle (SAS)", "Right triangles only", "Circles"], correctIndex: 1, explanation: "Cosine rule handles SAS and SSS cases." },
      { id: "q3", prompt: "In c²=a²+b²−2ab cos C, if C=90°, this reduces to:", options: ["Pythagoras' theorem", "The sine rule", "A linear equation", "Nothing special"], correctIndex: 0, explanation: "cos90°=0, so c²=a²+b²." },
      { id: "q4", prompt: "Given a=8, b=6, C=60°, which rule finds side c?", options: ["Sine rule", "Cosine rule", "Pythagoras only", "Cannot be found"], correctIndex: 1, explanation: "Two sides + included angle = cosine rule." },
      { id: "q5", prompt: "The sine rule states a/sinA equals:", options: ["b/sinB", "b×sinB", "sinB/b", "a×sinA"], correctIndex: 0, explanation: "All three ratios are equal." },
      { id: "q6", prompt: "For a triangle with 3 known sides, to find an angle you use:", options: ["Sine rule", "Cosine rule (rearranged)", "Area formula", "Cannot be found"], correctIndex: 1, explanation: "SSS → cosine rule rearranged for the angle." },
    ],
  },
  {
    id: "y10-simultaneous-equations",
    title: "Simultaneous Equations: Linear & Non-Linear",
    summary: "30-min block: solving pairs of linear equations, and a line intersecting a parabola.",
    estimatedMinutes: 30,
    year: 10,
    subject: "math",
    strand: "Algebra",
    content: [
      { type: "paragraph", text: "Simultaneous equations share a common solution. Solve linear pairs by substitution or elimination. For a line and a parabola, substitute the linear expression into the quadratic." },
      { type: "example", title: "Elimination", body: "2x+y=10, x−y=2. Add: 3x=12, x=4, then y=2." },
      { type: "example", title: "Line meets parabola", body: "y=x+1 and y=x². Substitute: x²=x+1 → x²−x−1=0 (solve with the quadratic formula)." },
    ],
    quiz: [
      { id: "q1", prompt: "Solve: x+y=7, x−y=1", options: ["x=4,y=3", "x=3,y=4", "x=1,y=6", "x=7,y=0"], correctIndex: 0, explanation: "Add equations: 2x=8, x=4, y=3." },
      { id: "q2", prompt: "Solve: 2x+3y=12, x=3", options: ["y=2", "y=6", "y=4", "y=3"], correctIndex: 0, explanation: "6+3y=12, 3y=6, y=2." },
      { id: "q3", prompt: "To solve a line meeting a parabola, you should:", options: ["Add the two y-values", "Substitute one equation into the other", "Ignore the parabola", "Average the equations"], correctIndex: 1, explanation: "Substitution reduces it to one quadratic in x." },
      { id: "q4", prompt: "Solve: y=2x, 3x+y=15", options: ["x=3,y=6", "x=5,y=10", "x=6,y=3", "x=15,y=30"], correctIndex: 0, explanation: "3x+2x=15, 5x=15, x=3, y=6." },
      { id: "q5", prompt: "A line and a parabola can intersect at most:", options: ["1 point", "2 points", "3 points", "Infinite points"], correctIndex: 1, explanation: "A quadratic equation has at most 2 real solutions." },
      { id: "q6", prompt: "Solve: 4x−y=5, y=3x", options: ["x=5,y=15", "x=1,y=3", "x=3,y=1", "x=−5,y=−15"], correctIndex: 0, explanation: "Substitute y=3x into 4x−y=5: 4x−3x=5, so x=5, then y=3(5)=15." },
    ],
  },
  {
    id: "y10-circle-geometry",
    title: "Circle Geometry",
    summary: "30-min block: chords, tangents, angle properties, and circumference/area applications.",
    estimatedMinutes: 30,
    year: 10,
    subject: "math",
    strand: "Space · Geometry",
    content: [
      { type: "paragraph", text: "Circles have special angle properties: the angle at the centre is twice the angle at the circumference (same arc); angles in a semicircle are right angles; a tangent meets a radius at 90°." },
      { type: "example", title: "Angle at centre", body: "If the angle at the circumference is 35°, the angle at the centre (same arc) is 70°." },
      { type: "list", items: ["Tangent ⊥ radius at the point of contact", "Angles in the same segment (same arc) are equal", "Opposite angles in a cyclic quadrilateral sum to 180°"] },
    ],
    quiz: [
      { id: "q1", prompt: "Angle at circumference is 40°. Angle at centre (same arc)?", options: ["20°", "40°", "80°", "140°"], correctIndex: 2, explanation: "Centre angle = 2 × circumference angle." },
      { id: "q2", prompt: "A tangent to a circle meets the radius at:", options: ["45°", "60°", "90°", "It varies"], correctIndex: 2, explanation: "Tangent-radius angle is always 90°." },
      { id: "q3", prompt: "An angle inscribed in a semicircle is:", options: ["45°", "60°", "90°", "180°"], correctIndex: 2, explanation: "Angle in a semicircle is always a right angle." },
      { id: "q4", prompt: "Opposite angles in a cyclic quadrilateral sum to:", options: ["90°", "180°", "270°", "360°"], correctIndex: 1, explanation: "Supplementary — always 180°." },
      { id: "q5", prompt: "Two angles subtend the same arc from the circumference. They are:", options: ["Always equal", "Always supplementary", "Unrelated", "Always 90°"], correctIndex: 0, explanation: "Angles in the same segment are equal." },
      { id: "q6", prompt: "Circumference of a circle with radius 7 (use π≈3.14):", options: ["21.98", "43.96", "153.86", "14"], correctIndex: 1, explanation: "C=2πr=2×3.14×7≈43.96." },
    ],
  },
  {
    id: "y10-probability-venn-conditional",
    title: "Probability: Venn Diagrams & Conditional Probability",
    summary: "30-min block: two-event Venn diagrams, tree diagrams, and conditional probability.",
    estimatedMinutes: 30,
    year: 10,
    subject: "math",
    strand: "Statistics & Probability",
    content: [
      { type: "formula", latex: "P(A|B) = \\frac{P(A \\cap B)}{P(B)}", note: "Conditional probability" },
      { type: "paragraph", text: "P(A∪B) = P(A) + P(B) − P(A∩B) avoids double-counting the overlap. Tree diagrams multiply along branches and add across separate branches." },
      { type: "example", title: "Conditional example", body: "P(rain)=0.3, P(rain and late)=0.12. P(late|rain)=0.12/0.3=0.4." },
    ],
    quiz: [
      { id: "q1", prompt: "P(A)=0.5, P(B)=0.4, P(A∩B)=0.2. Find P(A∪B).", options: ["0.7", "0.9", "0.1", "1.1"], correctIndex: 0, explanation: "0.5+0.4−0.2=0.7." },
      { id: "q2", prompt: "P(A∩B)=0.15, P(B)=0.3. Find P(A|B).", options: ["0.15", "0.45", "0.5", "0.05"], correctIndex: 2, explanation: "0.15/0.3=0.5." },
      { id: "q3", prompt: "Along the branches of a tree diagram, probabilities are:", options: ["Added", "Multiplied", "Subtracted", "Divided"], correctIndex: 1, explanation: "Multiply along a single path." },
      { id: "q4", prompt: "Two events with no overlap (P(A∩B)=0) are called:", options: ["Independent", "Mutually exclusive", "Conditional", "Equal"], correctIndex: 1, explanation: "Mutually exclusive events cannot both occur." },
      { id: "q5", prompt: "If A and B are independent, P(A∩B) equals:", options: ["P(A)+P(B)", "P(A)×P(B)", "P(A)−P(B)", "0"], correctIndex: 1, explanation: "Independence means the multiplication rule applies directly." },
      { id: "q6", prompt: "In a Venn diagram, the overlapping region represents:", options: ["A or B", "A and B (both)", "Neither", "A only"], correctIndex: 1, explanation: "The intersection is where both events occur." },
    ],
  },

  // ─── Year 11 (VCE Methods Units 1–2 style; extends "calculus-limits") ───
  {
    id: "y11-functions-notation",
    title: "Functions & Function Notation",
    summary: "30-min block: domain, range, function notation, and composite functions.",
    estimatedMinutes: 30,
    year: 11,
    subject: "math",
    strand: "Functions",
    content: [
      { type: "paragraph", text: "A function assigns exactly one output to each input. f(x) notation names the rule; f(3) means 'substitute 3 for x'. Domain = allowed inputs, range = resulting outputs." },
      { type: "example", title: "Evaluating", body: "f(x)=2x+1. f(3)=2(3)+1=7." },
      { type: "example", title: "Composite functions", body: "f(x)=x+2, g(x)=x². (g∘f)(x)=g(f(x))=g(x+2)=(x+2)²." },
    ],
    quiz: [
      { id: "q1", prompt: "f(x)=3x−4. Find f(2).", options: ["2", "6", "10", "−2"], correctIndex: 0, explanation: "3(2)−4=2." },
      { id: "q2", prompt: "For f(x)=√x, the domain is:", options: ["All reals", "x≥0", "x>0 only", "x≤0"], correctIndex: 1, explanation: "Square roots require non-negative inputs." },
      { id: "q3", prompt: "f(x)=x², g(x)=x+1. Find (f∘g)(2).", options: ["5", "9", "4", "3"], correctIndex: 1, explanation: "g(2)=3, f(3)=9." },
      { id: "q4", prompt: "A relation is a function if:", options: ["Every input has exactly one output", "Every output has one input", "It's always linear", "It has no domain restrictions"], correctIndex: 0, explanation: "This is the vertical line test principle." },
      { id: "q5", prompt: "For f(x)=1/(x−3), which value must be excluded from the domain?", options: ["0", "3", "−3", "1"], correctIndex: 1, explanation: "Division by zero is undefined at x=3." },
      { id: "q6", prompt: "The range of a function is the set of possible:", options: ["Inputs", "Outputs", "Both", "Neither"], correctIndex: 1, explanation: "Range = all resulting y-values." },
    ],
  },
  {
    id: "y11-polynomial-exponential-functions",
    title: "Polynomial & Exponential Functions",
    summary: "30-min block: cubic/quartic shape features and exponential growth/decay models.",
    estimatedMinutes: 30,
    year: 11,
    subject: "math",
    strand: "Functions",
    content: [
      { type: "paragraph", text: "Polynomial degree determines the maximum number of turning points and x-intercepts. Exponential functions y=a·bˣ model growth (b>1) or decay (0<b<1)." },
      { type: "example", title: "Exponential growth", body: "Population P=200×1.05ᵗ grows 5% each year. After 3 years: 200×1.05³≈231.5." },
      { type: "list", items: ["A cubic can have up to 2 turning points and 3 x-intercepts", "Exponential functions never cross the x-axis (horizontal asymptote at y=0)"] },
    ],
    quiz: [
      { id: "q1", prompt: "A cubic function can have at most how many x-intercepts?", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "Degree 3 → up to 3 real roots." },
      { id: "q2", prompt: "In y=a·bˣ, decay occurs when:", options: ["b>1", "0<b<1", "b=1", "b<0"], correctIndex: 1, explanation: "A base between 0 and 1 shrinks over time." },
      { id: "q3", prompt: "Exponential functions have a horizontal asymptote at:", options: ["x=0", "y=0 (typically)", "y=1", "There is none"], correctIndex: 1, explanation: "The curve approaches but never reaches y=0." },
      { id: "q4", prompt: "$500 grows at 8% p.a. compound. Value after 2 years?", options: ["$540", "$583.20", "$580", "$600"], correctIndex: 1, explanation: "500×1.08²=583.20." },
      { id: "q5", prompt: "A quartic (degree 4) can have at most how many turning points?", options: ["2", "3", "4", "5"], correctIndex: 1, explanation: "Degree n → at most n−1 turning points." },
      { id: "q6", prompt: "Which grows faster eventually: linear or exponential?", options: ["Linear always", "Exponential always eventually overtakes", "They're equal", "Depends only on intercept"], correctIndex: 1, explanation: "Exponential growth eventually outpaces any linear function." },
    ],
  },
  {
    id: "y11-intro-differentiation",
    title: "Introduction to Differentiation",
    summary: "30-min block: the power rule, and finding gradients of tangents — extends the limits idea from 'Limits & Rates of Change'.",
    estimatedMinutes: 30,
    year: 11,
    subject: "math",
    strand: "Calculus",
    content: [
      { type: "formula", latex: "\\frac{d}{dx}(x^n) = n x^{n-1}", note: "Power rule" },
      { type: "paragraph", text: "The derivative f'(x) gives the gradient of the tangent to the curve at any point x. Differentiate term by term." },
      { type: "example", title: "Worked example", body: "f(x)=3x²+2x−5. f'(x)=6x+2. Gradient at x=1: f'(1)=8." },
    ],
    quiz: [
      { id: "q1", prompt: "Differentiate: f(x)=x³", options: ["3x²", "x²", "3x", "x⁴"], correctIndex: 0, explanation: "Power rule: 3x^(3-1)=3x²." },
      { id: "q2", prompt: "Differentiate: f(x)=5x²+3x", options: ["10x+3", "5x+3", "10x", "5x²+3"], correctIndex: 0, explanation: "d/dx(5x²)=10x, d/dx(3x)=3." },
      { id: "q3", prompt: "The derivative of a constant (e.g. 7) is:", options: ["7", "1", "0", "x"], correctIndex: 2, explanation: "Constants have zero gradient — they don't change." },
      { id: "q4", prompt: "f(x)=4x³−2x. Find f'(2).", options: ["46", "10", "20", "44"], correctIndex: 0, explanation: "f'(x)=12x²−2, f'(2)=48−2=46." },
      { id: "q5", prompt: "The derivative represents:", options: ["The area under a curve", "The gradient of the tangent at a point", "The y-intercept", "The domain"], correctIndex: 1, explanation: "f'(x) = instantaneous rate of change = tangent gradient." },
      { id: "q6", prompt: "Differentiate: f(x)=x", options: ["0", "1", "x", "x²"], correctIndex: 1, explanation: "x=x¹, derivative = 1×x⁰=1." },
    ],
  },
  {
    id: "y11-trig-functions-radians",
    title: "Trigonometric Functions & Radians",
    summary: "30-min block: radian measure, and the sine/cosine graphs and their key features.",
    estimatedMinutes: 30,
    year: 11,
    subject: "math",
    strand: "Functions · Trigonometry",
    content: [
      { type: "paragraph", text: "Radians measure angles using arc length: 2π radians = 360°. Senior maths uses radians almost exclusively because calculus formulas depend on it." },
      { type: "formula", latex: "\\theta_{rad} = \\theta_{deg} \\times \\frac{\\pi}{180}", note: "Degrees to radians" },
      { type: "example", title: "Graph features", body: "y=sin(x) has amplitude 1, period 2π, and passes through (0,0). y=cos(x) has the same shape, shifted π/2 left." },
    ],
    quiz: [
      { id: "q1", prompt: "Convert 180° to radians.", options: ["π", "2π", "π/2", "90"], correctIndex: 0, explanation: "180×π/180=π." },
      { id: "q2", prompt: "The period of y=sin(x) is:", options: ["π", "2π", "π/2", "1"], correctIndex: 1, explanation: "One full sine wave repeats every 2π." },
      { id: "q3", prompt: "The amplitude of y=3sin(x) is:", options: ["1", "3", "2π", "π"], correctIndex: 1, explanation: "The coefficient in front sets the amplitude." },
      { id: "q4", prompt: "Convert π/2 radians to degrees.", options: ["45°", "90°", "180°", "60°"], correctIndex: 1, explanation: "(π/2)×(180/π)=90." },
      { id: "q5", prompt: "sin(0) equals:", options: ["1", "0", "−1", "Undefined"], correctIndex: 1, explanation: "The sine curve starts at zero." },
      { id: "q6", prompt: "cos(0) equals:", options: ["0", "1", "−1", "π"], correctIndex: 1, explanation: "The cosine curve starts at its maximum, 1." },
    ],
  },
  {
    id: "y11-discrete-random-variables",
    title: "Probability & Discrete Random Variables",
    summary: "30-min block: probability distribution tables, expected value, and variance for discrete random variables.",
    estimatedMinutes: 30,
    year: 11,
    subject: "math",
    strand: "Statistics & Probability",
    content: [
      { type: "formula", latex: "E(X) = \\sum x \\cdot P(X=x)", note: "Expected value" },
      { type: "paragraph", text: "A discrete random variable takes specific separate values, each with its own probability. All probabilities in the table must sum to 1." },
      { type: "example", title: "Worked example", body: "X: 1,2,3 with P: 0.2,0.5,0.3. E(X)=1(0.2)+2(0.5)+3(0.3)=0.2+1+0.9=2.1." },
    ],
    quiz: [
      { id: "q1", prompt: "All probabilities in a distribution table must sum to:", options: ["0", "0.5", "1", "100"], correctIndex: 2, explanation: "Total probability across all outcomes is always 1." },
      { id: "q2", prompt: "X: 0,1 with P: 0.4, 0.6. Find E(X).", options: ["0.4", "0.6", "1", "0.5"], correctIndex: 1, explanation: "0(0.4)+1(0.6)=0.6." },
      { id: "q3", prompt: "Expected value is best described as:", options: ["The most likely single outcome", "The long-run average outcome", "The maximum possible value", "Always a whole number"], correctIndex: 1, explanation: "E(X) is a weighted average, not necessarily an achievable single value." },
      { id: "q4", prompt: "X: 1,2,3,4 each with equal probability. Find P(X=2).", options: ["0.5", "0.25", "0.2", "1"], correctIndex: 1, explanation: "Four equally likely outcomes: 1/4=0.25." },
      { id: "q5", prompt: "A discrete random variable's values are:", options: ["Always continuous", "Countable/separate", "Always negative", "Undefined"], correctIndex: 1, explanation: "Discrete = distinct, countable values (unlike continuous)." },
      { id: "q6", prompt: "X: 5,10 with P(X=5)=0.3. Find P(X=10).", options: ["0.3", "0.5", "0.7", "1.3"], correctIndex: 2, explanation: "Probabilities must total 1: 1−0.3=0.7." },
    ],
  },

  // ─── Year 12 (VCE Methods Units 3–4 style; extends "probability-distributions") ───
  {
    id: "y12-differentiation-rules",
    title: "Differentiation Rules: Product, Quotient & Chain",
    summary: "30-min block: differentiating products, quotients and composite functions.",
    estimatedMinutes: 30,
    year: 12,
    subject: "math",
    strand: "Calculus",
    content: [
      { type: "formula", latex: "\\frac{d}{dx}[f(x)g(x)] = f'(x)g(x)+f(x)g'(x)", note: "Product rule" },
      { type: "formula", latex: "\\frac{d}{dx}[f(g(x))] = f'(g(x)) \\cdot g'(x)", note: "Chain rule" },
      { type: "example", title: "Chain rule example", body: "y=(3x+1)⁴. dy/dx = 4(3x+1)³ × 3 = 12(3x+1)³." },
    ],
    quiz: [
      { id: "q1", prompt: "Differentiate y=(2x+3)⁵ using the chain rule.", options: ["5(2x+3)⁴", "10(2x+3)⁴", "5(2x+3)⁴×2", "2(2x+3)⁵"], correctIndex: 1, explanation: "5(2x+3)⁴ × 2 = 10(2x+3)⁴." },
      { id: "q2", prompt: "The product rule is used when differentiating:", options: ["A single term", "Two functions multiplied together", "A constant", "A sum of terms"], correctIndex: 1, explanation: "Product rule handles f(x)·g(x)." },
      { id: "q3", prompt: "For y=x²·sin(x), which rule applies?", options: ["Power rule only", "Product rule", "Quotient rule", "None"], correctIndex: 1, explanation: "Two functions multiplied → product rule." },
      { id: "q4", prompt: "The chain rule is used for:", options: ["Sums of functions", "Composite functions (function of a function)", "Constants only", "Straight lines"], correctIndex: 1, explanation: "Chain rule 'unwraps' nested functions." },
      { id: "q5", prompt: "Differentiate y=(x²+1)³ at the outer layer first step:", options: ["3(x²+1)²", "3(x²+1)²×2x", "(x²+1)²", "2x"], correctIndex: 1, explanation: "Outer derivative × inner derivative: 3(x²+1)²×2x." },
      { id: "q6", prompt: "Quotient rule is used when differentiating:", options: ["f(x)/g(x)", "f(x)+g(x)", "f(x)×g(x)", "f(g(x)) only"], correctIndex: 0, explanation: "Quotient rule is specifically for division of two functions." },
    ],
  },
  {
    id: "y12-applications-differentiation",
    title: "Applications of Differentiation: Optimisation",
    summary: "30-min block: finding maxima/minima and solving real-world optimisation problems.",
    estimatedMinutes: 30,
    year: 12,
    subject: "math",
    strand: "Calculus",
    content: [
      { type: "paragraph", text: "At a maximum or minimum, f'(x)=0. Solve for x, then check whether it's a max or min (via the second derivative or a sign check either side)." },
      { type: "example", title: "Optimisation", body: "Maximise area A=x(20−x). A'=20−2x. Set to 0: x=10. Max area = 10×10=100." },
      { type: "callout", tone: "tip", text: "Real problems: minimise cost, maximise profit/area/volume — always start by writing one variable in terms of the other using a constraint." },
    ],
    quiz: [
      { id: "q1", prompt: "At a turning point (max or min), f'(x) equals:", options: ["1", "0", "Undefined always", "−1"], correctIndex: 1, explanation: "The gradient is zero at a turning point." },
      { id: "q2", prompt: "A=x(30−x). Find x that maximises A.", options: ["10", "15", "20", "30"], correctIndex: 1, explanation: "A'=30−2x=0 → x=15." },
      { id: "q3", prompt: "If f''(x)>0 at a critical point, it is a:", options: ["Maximum", "Minimum", "Point of inflection", "Cannot tell"], correctIndex: 1, explanation: "Positive second derivative = concave up = minimum." },
      { id: "q4", prompt: "If f''(x)<0 at a critical point, it is a:", options: ["Maximum", "Minimum", "Undefined", "Zero"], correctIndex: 0, explanation: "Negative second derivative = concave down = maximum." },
      { id: "q5", prompt: "The first step in an optimisation problem is usually:", options: ["Differentiate immediately", "Write an equation for the quantity to optimise using the constraint", "Guess the answer", "Integrate"], correctIndex: 1, explanation: "Set up the function first, then differentiate." },
      { id: "q6", prompt: "A rectangle has perimeter 40. Maximise area — what shape results?", options: ["A very thin rectangle", "A square (10×10)", "A circle", "Cannot be determined"], correctIndex: 1, explanation: "For fixed perimeter, a square maximises rectangular area." },
    ],
  },
  {
    id: "y12-integration",
    title: "Integration & Area Under Curves",
    summary: "30-min block: antidifferentiation, the power rule for integration, and definite integrals as area.",
    estimatedMinutes: 30,
    year: 12,
    subject: "math",
    strand: "Calculus",
    content: [
      { type: "formula", latex: "\\int x^n \\, dx = \\frac{x^{n+1}}{n+1} + c", note: "Reverse power rule (n ≠ −1)" },
      { type: "paragraph", text: "Integration is the reverse of differentiation. A definite integral ∫ₐᵇ f(x)dx calculates the signed area between the curve and the x-axis from a to b." },
      { type: "example", title: "Worked example", body: "∫x² dx = x³/3 + c. ∫₀² x² dx = [x³/3]₀² = 8/3 − 0 = 8/3." },
    ],
    quiz: [
      { id: "q1", prompt: "∫x³ dx =", options: ["x⁴/4 + c", "3x² + c", "x⁴ + c", "4x³ + c"], correctIndex: 0, explanation: "Reverse power rule: exponent+1, divide by new exponent." },
      { id: "q2", prompt: "A definite integral calculates:", options: ["A gradient", "An area (signed) under a curve", "A domain", "A limit only"], correctIndex: 1, explanation: "That's the geometric meaning of ∫ₐᵇ f(x)dx." },
      { id: "q3", prompt: "∫5 dx =", options: ["5x + c", "5 + c", "x + c", "0"], correctIndex: 0, explanation: "Integrating a constant gives (constant)×x + c." },
      { id: "q4", prompt: "∫₀³ 2x dx =", options: ["6", "9", "3", "18"], correctIndex: 1, explanation: "∫2x dx=x²; [x²]₀³=9−0=9." },
      { id: "q5", prompt: "Integration is the reverse process of:", options: ["Addition", "Differentiation", "Multiplication", "Simplifying"], correctIndex: 1, explanation: "Integration 'undoes' differentiation." },
      { id: "q6", prompt: "The '+c' in an indefinite integral represents:", options: ["An error", "An unknown constant (any constant's derivative is 0)", "The gradient", "The domain"], correctIndex: 1, explanation: "Since constants vanish under differentiation, they're unknown when reversing." },
    ],
  },
  {
    id: "y12-exponential-logarithmic",
    title: "Exponential & Logarithmic Functions",
    summary: "30-min block: log laws, solving exponential equations, and the natural logarithm.",
    estimatedMinutes: 30,
    year: 12,
    subject: "math",
    strand: "Functions",
    content: [
      { type: "paragraph", text: "Logarithms answer 'what power?'. logₐ(x)=y means aʸ=x. The natural log ln(x) uses base e (≈2.718), central to calculus of exponential functions." },
      { type: "list", items: ["log(ab) = log a + log b", "log(a/b) = log a − log b", "log(aⁿ) = n log a"] },
      { type: "example", title: "Solving exponentials", body: "3ˣ=81 → 3ˣ=3⁴ → x=4. Or using logs: x=log(81)/log(3)=4." },
    ],
    quiz: [
      { id: "q1", prompt: "Solve: 2ˣ=32", options: ["4", "5", "6", "16"], correctIndex: 1, explanation: "2⁵=32, so x=5." },
      { id: "q2", prompt: "log(20) can be split as:", options: ["log20", "log2 + log10", "log2 × log10", "log2 − log10"], correctIndex: 1, explanation: "log(ab)=log a + log b, and 2×10=20." },
      { id: "q3", prompt: "logₐ(x)=y means:", options: ["a=xʸ", "aʸ=x", "y=x×a", "x=y+a"], correctIndex: 1, explanation: "That's the definition of a logarithm." },
      { id: "q4", prompt: "log(x⁴) equals:", options: ["4log(x)", "log(x)+4", "4+log(x)", "log(4x)"], correctIndex: 0, explanation: "Power law: log(aⁿ)=n log a." },
      { id: "q5", prompt: "The natural logarithm ln(x) uses base:", options: ["10", "2", "e (≈2.718)", "1"], correctIndex: 2, explanation: "ln is log base e." },
      { id: "q6", prompt: "log(100)/log(10) simplifies (base 10) to:", options: ["1", "2", "10", "100"], correctIndex: 1, explanation: "log(100)=2, log(10)=1, so 2/1=2." },
    ],
  },
  {
    id: "y12-continuous-distributions-normal",
    title: "Continuous Distributions & the Normal Distribution",
    summary: "30-min block: probability density functions, the normal distribution, and z-scores — extends 'Probability Distributions'.",
    estimatedMinutes: 30,
    year: 12,
    subject: "math",
    strand: "Statistics & Probability",
    content: [
      { type: "paragraph", text: "Continuous random variables (height, time, weight) use a probability density function; probability = area under the curve. The normal distribution is symmetric, bell-shaped, defined by mean μ and standard deviation σ." },
      { type: "formula", latex: "z = \\frac{x - \\mu}{\\sigma}", note: "z-score standardises a value" },
      { type: "list", items: ["68% of data within 1σ of the mean", "95% within 2σ", "99.7% within 3σ (the empirical rule)"] },
    ],
    quiz: [
      { id: "q1", prompt: "For a continuous random variable, probability is calculated as:", options: ["A single point value", "Area under the density curve", "The mean only", "Always 1"], correctIndex: 1, explanation: "Unlike discrete variables, continuous probability is an area (P(X=exact value)=0)." },
      { id: "q2", prompt: "Mean=100, SD=15. Find the z-score for x=130.", options: ["1", "2", "3", "0.5"], correctIndex: 1, explanation: "(130−100)/15=2." },
      { id: "q3", prompt: "Approximately what % of normal data lies within 1 standard deviation?", options: ["50%", "68%", "95%", "99.7%"], correctIndex: 1, explanation: "The empirical rule: 68% within 1σ." },
      { id: "q4", prompt: "The normal distribution curve is:", options: ["Skewed right always", "Symmetric and bell-shaped", "A straight line", "Only positive values"], correctIndex: 1, explanation: "Symmetry around the mean is its defining shape." },
      { id: "q5", prompt: "A z-score of 0 means the value is:", options: ["At the maximum", "Equal to the mean", "Equal to the standard deviation", "Impossible"], correctIndex: 1, explanation: "z=0 → x=μ exactly." },
      { id: "q6", prompt: "Approximately what % lies within 2 standard deviations?", options: ["68%", "95%", "99.7%", "100%"], correctIndex: 1, explanation: "Empirical rule: ~95% within 2σ." },
    ],
  },
];
